In [4]:
import numpy as np

In [5]:
newArr = np.random.randint(10,25,size = (4,4))
newArr

array([[11, 13, 15, 12],
       [23, 13, 10, 20],
       [22, 19, 13, 20],
       [16, 19, 16, 10]])

In [6]:
# copy
x_new = newArr[2:4,2:4].copy() # creates new location for x_new
x_new

array([[13, 20],
       [16, 10]])

In [7]:
x_new1 = x_new
print("X_New:",id(x_new))
print("X_New1",id(x_new1))
print("newArr:",id(newArr))

X_New: 140252608972336
X_New1 140252608972336
newArr: 140252608972048


### Vstack & Hstack

In [8]:
# New nnd arrays can be created
# vstack() -> vertical stack, rows will be increased, NO OF COLUMNS SHOULD BE SAME
# hstack() -> horizontal stack, one beside another,columns will be increased, NO OF ROWS SHOULD BE SAME
# vstack and hstack works for 3 dimensional array only

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[8,9,10], [11,12,13]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 8  9 10]
 [11 12 13]]


In [10]:
vs = np.vstack([arr1,arr2])
vs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [11]:
hs = np.hstack([arr1,arr2])
hs

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

### Concatenate

In [12]:
# concatenate - take a sequence (tuple,list) and join them along with axis
# unlike vstack and hstack it works forks for ndimension
# rows = 0, columns = 1 in concatenate axis

In [13]:
rowWiseConcat = np.concatenate([arr1,arr2], axis = 0) #works as vstack 
rowWiseConcat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [14]:
colWiseConcat = np.concatenate([arr1,arr2], axis = 1) #works as hstack
colWiseConcat

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [15]:
arr3 = np.array([[11,12,13],[14,15,16], [17,18,19]])
arr4 = np.array([[14,15],[17,18]])
arr6 = np.array([[14,15],[16,17],[18,19]])

In [16]:
print("Arr1:\n",arr1)
print("Shape:",arr1.shape)
print("\nArr3:\n",arr3)
print("Shape:",arr3.shape)
print("\nArr4:\n",arr4)
print("Shape:",arr4.shape)
print("\nArr6:\n",arr6)
print("Shape:",arr6.shape)

Arr1:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Arr3:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Shape: (3, 3)

Arr4:
 [[14 15]
 [17 18]]
Shape: (2, 2)

Arr6:
 [[14 15]
 [16 17]
 [18 19]]
Shape: (3, 2)


In [17]:
arr5 = np.vstack([arr1,arr3]) # no error becauuse no of columns are same
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
arr6 = np.vstack([arr3,arr4]) #error because in vstack no of columns should be same
arr6

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [24]:
arr7 = np.hstack([arr3,arr6]) #no error because in sstack no of rows should be same, and here it is
arr7

array([[11, 12, 13, 14, 15],
       [14, 15, 16, 16, 17],
       [17, 18, 19, 18, 19]])

In [23]:
a = np.arange(9) 
np.split(a,3) # works only if 3 is factor of 9 or mentioned value is factor of total no opf elemnts

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
# casting - we can convert data type into anothere data type

In [22]:
arr8 = np.array([[1,2,3],[4,5,6]])
print(arr8.dtype)

int64


In [25]:
# astype() - we can cast to another dtype

arr9 = arr8.astype(np.float64)
print(arr9.dtype)

float64


In [20]:
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
np.diag(np.rot90(arr3))

array([13, 15, 17])

In [ ]:
# ndim - It displays dimension of an array

arr3.ndim