In [1]:
#randn - It generates random float number

In [3]:
import numpy as np

In [73]:
arr1 = np.random.randn(10)

In [74]:
arr1

array([-0.63205782, -0.02978247,  0.45547652, -0.82464246, -0.04421276,
       -1.35526928, -0.9746586 ,  2.30337124, -1.06800289,  0.23897763])

In [22]:
# numpy.arange() - it is an inbuilt function that returns evenlly spaced values, within a givin range.
# Syntax: numpy.arange(start,stop,step)

In [29]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
arr3 = np.arange(10,20,2)
arr3

array([10, 12, 14, 16, 18])

In [31]:
# Other ways to create arrays
# ones- to create arrays of one.
# zeroes - to create arrays of zeros
# eye - to create identity matrix  -> Idenntity matrix is matrix with diagonal 1
# np.diag - to create diagonal matrix

In [32]:
# ones
arr4 = np.ones(10)
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
arr5 = np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
arr6 = np.eye(3,3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
arr7 = np.eye(3,3,1) # Move position by 1 to right
arr7

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [50]:
arr8 = np.diag((5,5,5)) #nuum oof values you decide matrix size- here 3 5's means 3 X 3 matrix
arr8

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [51]:
# Acessing Single Dimennsion Array
# Indexing starts from 0 left to right annd it starts from -1 from right to left

In [53]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
newArr[0]

0

In [55]:
newArr[-1]

9

In [56]:
# we cann access multiple elements using colon :
newArr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
newArr[2:5]

array([2, 3, 4])

In [61]:
newArr1 = np.arange(10,30,2)
newArr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [62]:
newArr1[2:5] # we cann access continuouus elements but cannnoot access non continuouus elements

array([14, 16, 18])

In [64]:
newArr1[0:5:2] # jusmps 2 step

array([10, 14, 18])

In [76]:
# Multidimensional arrays
# In multidimenional arrays rows and columns can be accessed using , seperator
# Multiple rows can be accessed using : & multiple column can be accessed using :
# using , we can seprate rows & columns 

newArr2 = np.random.randint(5,15,size = (3,3))
newArr2

array([[ 6, 14,  5],
       [ 6, 10, 12],
       [ 9,  7,  5]])

In [66]:
newArr2[1] # Prints rows here 1 row

newArr2[0:2] # prints 2 rows from 0 to 1

array([6, 5, 5])

In [77]:
newArr2[0:2,0:1]

array([[6],
       [6]])

In [80]:
newArr2[1,1]

10

In [81]:
newArr2[1:2,1:2] # Another way to access rows annd columns

array([[10]])

In [82]:
myArr = newArr2[1,1] # this creates integer
myArr

10

In [83]:
type(myArr)

numpy.int64

In [84]:
myArr2 = newArr2[1:2,1:2] # This method creates array instead of direct access creates integer
myArr2

array([[10]])

In [85]:
type(myArr2)

numpy.ndarray

In [86]:
newArr3 = np.random.randint(11,45, size = (4,5))
newArr3

array([[44, 28, 21, 13, 16],
       [12, 13, 27, 26, 33],
       [15, 25, 44, 24, 33],
       [28, 43, 34, 13, 25]])

In [91]:
newArr3[1:3,2:4]

array([[27, 26],
       [44, 24]])

In [92]:
newArr3[1:3,1:4]

array([[13, 27, 26],
       [25, 44, 24]])